services:
  valkey-node-1:
    image: valkey/valkey:latest
    command: valkey-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --requirepass ${VALKEY_PASSWORD}
    volumes:
      - ./data1:/data
    network_mode: host
  valkey-node-2:
    image: valkey/valkey:latest
    command: valkey-server --port 6380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --requirepass ${VALKEY_PASSWORD}
    volumes:
      - ./data2:/data
    network_mode: host
  valkey-node-3:
    image: valkey/valkey:latest
    command: valkey-server --port 6381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --requirepass ${VALKEY_PASSWORD}
    volumes:
      - ./data3:/data
    network_mode: host
  valkey-cluster-creator:
    image: valkey/valkey:latest
    command: valkey-cli --cluster create ${NODE_IP}:6379 ${NODE_IP}:6380 ${NODE_IP}:6381 -a ${VALKEY_PASSWORD} --cluster-yes
    volumes:
      - ./data3:/data
    network_mode: host
    depends_on:
      - valkey-node-1
      - valkey-node-2
      - valkey-node-3

volumes:
  data1:
    driver: local
  data3:
    driver: local
  data2:
    driver: local
